FROM mysql:8.0

# Copier le script SQL qui est dans le même dossier
COPY init.sql /docker-entrypoint-initdb.d/init.sql

# S'assurer que le fichier a les bonnes permissions
RUN chmod 644 /docker-entrypoint-initdb.d/init.sql
